server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb+srv://amcclelland21:g1oYKbFdKn0cwl9E@cluster0.9oqfb.mongodb.net/rebekahs-recipes?retryWrites=true&w=majority
  security:
    user:
      name: admin
      password: andrew123
